version: "3.9"

services:
  server:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: "lamoda"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "putingay"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-database", "postgres://postgres:putingay@postgres:5432/lamoda?sslmode=disable", "-path", "/migrations", "up"]
    depends_on:
      postgres:
        condition: service_healthy