version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "lamoda"
      POSTGRES_USER: "hymiside"
      POSTGRES_PASSWORD: "putingay"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5430:5432"
