openapi: 3.0.0
info:
  title: Lamoda Tech API
  description: API for managing product reservations and availability.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
    description: Local development server
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /products/availability:
    get:
      summary: Get product availability at a warehouse
      parameters:
        - in: query
          name: warehouse_id
          schema:
            type: integer
          required: true
          description: The warehouse ID to get product availability
      responses:
        '200':
          description: Product availability information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductAvailability'

  /reservation-products:
    post:
      summary: Reserve products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationRequest'
      responses:
        '200':
          description: Reservation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationResponse'

    delete:
      summary: Cancel product reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelReservationRequest'
      responses:
        '200':
          description: Reservation cancelled

  /confirm-reservation:
    post:
      summary: Confirm reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmReservationRequest'
      responses:
        '200':
          description: Reservation confirmed

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        part_number:
          type: string
        title:
          type: string
        width:
          type: integer
        height:
          type: integer
        depth:
          type: integer

    ProductAvailability:
      type: object
      properties:
        Product:
          $ref: '#/components/schemas/Product'
        WarehouseAvail:
          type: boolean
        Quantity:
          type: integer

    ReservationRequest:
      type: object
      properties:
        part_numbers:
          type: array
          items:
            type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float

    ReservationResponse:
      type: object
      properties:
        reservation_id:
          type: string

    CancelReservationRequest:
      type: object
      properties:
        reservation_id:
          type: string
        part_numbers:
          type: array
          items:
            type: string

    ConfirmReservationRequest:
      type: object
      properties:
        reservation_id:
          type: string
        part_numbers:
          type: array
          items:
            type: string